package com.example.pruebaskotlin

/**
 * EJERCICIO 1
 *
 * HACED UNA APP CUYA VENTANA INICIAL ESTÉ DIVIDA EN 4 RECTÁNGULOS DEL MISMO TAMAÑO
 * Y QUE OCUPEN TODA LA SUPERFICIE DE LA PANTALLA Y PONER UN COLOR DE FONDO / BACKGROUND EN CADA UNO DE ELLOS, DISTINTO AL NEGRO.
 *
 * CUANDO EL USUARIO TOQUE UN RECTÁNGULO, DEBE PASAR A FONDO NEGRO. SI LO TOCA OTRA VEZ, YA NO CAMBIA DE COLOR MÁS. SE QUEDA EN NEGRO.
 *CUANDO TODOS LOS RECTÁNGULOS ESTÉN EN NEGRO, LANZAR UN SNACK BAR CON EN TEXTO “JUEGO TERMINADO” Y FINALIZAR LA ACTIVDAD.
 *
 *
 * EXTRA: UNA VEZ CONSEGUIDO EL FUNCIONAMIENTO ANTERIOR, HACED QUE LA APP GESTIONE LOS CAMBIOS DE ORIENTACIÓN.
 * ES DECIR, QUE SI GIRO EL MÓVIL EN HORIZONTAL, LA APLICACIÓN TENGA MEMORIA Y LOS RECTÁNGULOS QUE YA FUERON TOCADOS Y ERAN NEGROS, PERMANEZCAN EN NEGRO.



EJERCICIO 2

HACED UNA APP QUE SE LLAME PRENSA DEPORTIVA. SU VENTANA INICIAL DEBE MOSTRAR LAS SIGUIENTES PAGINAS WEBS DE INICIO DE LOS SIGUIENTES SITIOS:  https://as.com/  https://www.marca.com/ https://www.mundodeportivo.com/ Y https://www.sport.es/es/

LOS RECTÁNGULOS QUE MUESTREN CADA WEB, DEBEN OCUPAR TODO EL ANCHO DE LA PANTALLA Y UN LARGO VARIABLE, DEFINIDO POR EL DISEÑADOR, PERO DE MODO QUE LA LISTA DE WEBS, DESBORDEN EL ESPACIO VERTICAL DE LA PANTALLA Y NOS VEAMOS OBLIGADOS A USAR EN EL DISEÑO UN SCROLLVIEW


EN CADA WEB, DEBE SUPERPONERSE UN BOTÓN ALINEADO ABAJO A LA DERECHA,  QUE DIGA APAREZCA CON EL TEXTO "VISTAR WEB", DE MODO QUE CUANDO SE CLIQUE, SE ABRA UNA VENTANA NUEVA DEL NAVEGADOR CON LA WEB SELECCIONADA.



 */
fun main() {
    val nombre = "ADIOS"

        //println(nombre.length)

    if (nombre.length==4) {
        println("La longitud de la cadena es 4")
        println("La longitud de la cadena es par")
    }
    println("Esto se acaba")
}